import 'package:flutter/material.dart';
import 'package:login_page/model/notification_model.dart';
import 'package:login_page/utils/app_color.dart';

class NotificationData {
  static List<NotificationModel> getNotifications() {
    return [
      NotificationModel(
        id: 1,
        type: 'payroll',
        icon: Icons.attach_money_rounded,
        title: 'Payroll Processing Complete',
        message: 'Monthly payroll for December has been processed successfully.',
        time: '2 hours ago',
        read: false,
        color: AppColor.green,
      ),
      NotificationModel(
        id: 2,
        type: 'employee',
        icon: Icons.person_rounded,
        title: 'New Employee Onboarding',
        message: 'Sarah Johnson has completed onboarding documents.',
        time: '3 hours ago',
        read: false,
        color: AppColor.blue,
      ),
      NotificationModel(
        id: 3,
        type: 'alert',
        icon: Icons.warning_amber_rounded,
        title: 'Attendance Alert',
        message: '5 employees marked absent today without prior notice.',
        time: '5 hours ago',
        read: false,
        color: AppColor.red,
      ),
      NotificationModel(
        id: 4,
        type: 'calendar',
        icon: Icons.calendar_month_rounded,
        title: 'Upcoming Performance Reviews',
        message: '12 performance reviews scheduled for next week.',
        time: '1 day ago',
        read: true,
        color: AppColor.purple,
      ),
      NotificationModel(
        id: 5,
        type: 'success',
        icon: Icons.check_circle_rounded,
        title: 'Leave Request Approved',
        message: 'Michael Chen\'s leave request has been approved.',
        time: '1 day ago',
        read: true,
        color: AppColor.green,
      ),
      NotificationModel(
        id: 6,
        type: 'pending',
        icon: Icons.access_time_rounded,
        title: 'Pending Approvals',
        message: 'You have 8 leave requests awaiting approval.',
        time: '2 days ago',
        read: true,
        color: AppColor.orange,
      ),
      NotificationModel(
        id: 7,
        type: 'employee',
        icon: Icons.person_add_rounded,
        title: 'New Hire Welcome',
        message: 'Welcome package sent to 3 new employees.',
        time: '2 days ago',
        read: true,
        color: AppColor.blue,
      ),
      NotificationModel(
        id: 8,
        type: 'payroll',
        icon: Icons.receipt_rounded,
        title: 'Expense Report Submitted',
        message: 'Jessica Lee submitted expense report for \$450.',
        time: '3 days ago',
        read: true,
        color: AppColor.green,
      ),
      NotificationModel(
        id: 9,
        type: 'alert',
        icon: Icons.error_outline_rounded,
        title: 'System Maintenance',
        message: 'Scheduled maintenance on Sunday 2 AM - 4 AM.',
        time: '4 days ago',
        read: true,
        color: AppColor.orange,
      ),
      NotificationModel(
        id: 10,
        type: 'employee',
        icon: Icons.celebration_rounded,
        title: 'Work Anniversary',
        message: 'John Doe celebrates 5 years with the company!',
        time: '5 days ago',
        read: true,
        color: AppColor.purple,
      ),
    ];
  }
}
